name: CI
on:
  pull_request:
    branches: [dev]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.5"
      - run: |
          pip install Flask
          pip install flask_sqlalchemy
          pip install flask_migrate
          pip install flask_login
          pip install flask_mail
          pip install flask_bootstrap
          pip install flask_moment
          pip install flask_babel
          pip install python-dotenv
        env: 
          CI: true
      - name: Build project
        if: github.event_name == "push"
        run: python3 -m pip install --upgrade pip

      - name: Deploy to Staging project
        if: github.event_name == "push"
